// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: api/v1/sre.proto

package srev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CollectorServiceClient is the client API for CollectorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CollectorServiceClient interface {
	// Agent streams metrics to Collector (Client Streaming)
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (CollectorService_StreamMetricsClient, error)
	// Real-time server streaming of alerts (Server Streaming)
	SubscribeAlerts(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (CollectorService_SubscribeAlertsClient, error)
}

type collectorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCollectorServiceClient(cc grpc.ClientConnInterface) CollectorServiceClient {
	return &collectorServiceClient{cc}
}

func (c *collectorServiceClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (CollectorService_StreamMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[0], "/sre.v1.CollectorService/StreamMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceStreamMetricsClient{stream}
	return x, nil
}

type CollectorService_StreamMetricsClient interface {
	Send(*Metric) error
	CloseAndRecv() (*MetricStreamResponse, error)
	grpc.ClientStream
}

type collectorServiceStreamMetricsClient struct {
	grpc.ClientStream
}

func (x *collectorServiceStreamMetricsClient) Send(m *Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *collectorServiceStreamMetricsClient) CloseAndRecv() (*MetricStreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MetricStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorServiceClient) SubscribeAlerts(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (CollectorService_SubscribeAlertsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CollectorService_ServiceDesc.Streams[1], "/sre.v1.CollectorService/SubscribeAlerts", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorServiceSubscribeAlertsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CollectorService_SubscribeAlertsClient interface {
	Recv() (*Alert, error)
	grpc.ClientStream
}

type collectorServiceSubscribeAlertsClient struct {
	grpc.ClientStream
}

func (x *collectorServiceSubscribeAlertsClient) Recv() (*Alert, error) {
	m := new(Alert)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CollectorServiceServer is the server API for CollectorService service.
// All implementations must embed UnimplementedCollectorServiceServer
// for forward compatibility
type CollectorServiceServer interface {
	// Agent streams metrics to Collector (Client Streaming)
	StreamMetrics(CollectorService_StreamMetricsServer) error
	// Real-time server streaming of alerts (Server Streaming)
	SubscribeAlerts(*SubscribeRequest, CollectorService_SubscribeAlertsServer) error
	mustEmbedUnimplementedCollectorServiceServer()
}

// UnimplementedCollectorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCollectorServiceServer struct {
}

func (UnimplementedCollectorServiceServer) StreamMetrics(CollectorService_StreamMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedCollectorServiceServer) SubscribeAlerts(*SubscribeRequest, CollectorService_SubscribeAlertsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeAlerts not implemented")
}
func (UnimplementedCollectorServiceServer) mustEmbedUnimplementedCollectorServiceServer() {}

// UnsafeCollectorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CollectorServiceServer will
// result in compilation errors.
type UnsafeCollectorServiceServer interface {
	mustEmbedUnimplementedCollectorServiceServer()
}

func RegisterCollectorServiceServer(s grpc.ServiceRegistrar, srv CollectorServiceServer) {
	s.RegisterService(&CollectorService_ServiceDesc, srv)
}

func _CollectorService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CollectorServiceServer).StreamMetrics(&collectorServiceStreamMetricsServer{stream})
}

type CollectorService_StreamMetricsServer interface {
	SendAndClose(*MetricStreamResponse) error
	Recv() (*Metric, error)
	grpc.ServerStream
}

type collectorServiceStreamMetricsServer struct {
	grpc.ServerStream
}

func (x *collectorServiceStreamMetricsServer) SendAndClose(m *MetricStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *collectorServiceStreamMetricsServer) Recv() (*Metric, error) {
	m := new(Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CollectorService_SubscribeAlerts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServiceServer).SubscribeAlerts(m, &collectorServiceSubscribeAlertsServer{stream})
}

type CollectorService_SubscribeAlertsServer interface {
	Send(*Alert) error
	grpc.ServerStream
}

type collectorServiceSubscribeAlertsServer struct {
	grpc.ServerStream
}

func (x *collectorServiceSubscribeAlertsServer) Send(m *Alert) error {
	return x.ServerStream.SendMsg(m)
}

// CollectorService_ServiceDesc is the grpc.ServiceDesc for CollectorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CollectorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sre.v1.CollectorService",
	HandlerType: (*CollectorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _CollectorService_StreamMetrics_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeAlerts",
			Handler:       _CollectorService_SubscribeAlerts_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/sre.proto",
}
